module.exports = {
    VERIFY_USER: 'VERIFY_USER',
    MESSAGE_SENT: 'MESSAGE_SENT',
    USER_CONNECTED: 'USER_CONNECTED',
    GET_USER_NAMES: 'GET_USER_NAMES',
    USER_NAMES_RECIEVED: 'USER_NAMES_RECIEVED'
};